import type { Butir } from '@/komponen/Galeri'

/** Dokumentasi bawaan dari company profile resmi, dipakai bila basis data belum terisi. */
export const BAWAAN: Butir[] = [
  { gambar: '/galeri/sec-h03-585-b0ba4753d0.jpg', judul: 'Kantor pusat Dharmapati di Purwakarta', kategori: 'Perusahaan' },
  { gambar: '/galeri/sec-h09-1834-f1d4dffa5d.jpg', judul: 'Staf administrasi', kategori: 'Perusahaan' },
  { gambar: '/galeri/sec-h09-1835-818c502bf0.jpg', judul: 'Staf HRD', kategori: 'Perusahaan' },
  { gambar: '/galeri/sec-h09-1836-9cb032e2e9.jpg', judul: 'Staf keuangan', kategori: 'Perusahaan' },
  { gambar: '/galeri/sec-h09-1837-791facb760.jpg', judul: 'Manajemen operasional', kategori: 'Perusahaan' },
  { gambar: '/galeri/sec-h11-2227-f0deb6570a.jpg', judul: 'Anggota memberi penghormatan di kantor', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h12-2432-751ec36794.jpg', judul: 'Regu jaga siap bertugas', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h11-2226-302a153b74.jpg', judul: 'Danru di pos jaga', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h11-2228-957aac55df.jpg', judul: 'Anggota Satpam wanita di lobi klien', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h11-2229-16362df3e0.jpg', judul: 'Anggota Satpam berseragam lengkap', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h12-2430-51100a94ed.jpg', judul: 'Apel anggota di area proyek', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h12-2429-f952f1bf2a.jpg', judul: 'Pengarahan sebelum bertugas', kategori: 'Pengamanan' },
  { gambar: '/galeri/sec-h13-2623-76ff6b0a4a.jpg', judul: 'Supervisi anggota di objek', kategori: 'Supervisi' },
  { gambar: '/galeri/sec-h13-2624-cbeec6cf6d.jpg', judul: 'Kunjungan supervisor ke lapangan', kategori: 'Supervisi' },
  { gambar: '/galeri/sec-h13-2625-faa8a2dd0b.jpg', judul: 'Apel pagi bersama supervisor', kategori: 'Supervisi' },
  { gambar: '/galeri/sec-h13-2626-bc51812beb.jpg', judul: 'Penjagaan area pergudangan', kategori: 'Supervisi' },
  { gambar: '/galeri/sec-h15-3019-12791fcf63.jpg', judul: 'Latihan bela diri', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h15-3020-a4bc0ea075.jpg', judul: 'Drill tongkat dan borgol', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h15-3023-d87c42ee17.jpg', judul: 'Drill pemadam kebakaran', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h15-3022-2cb5796d8c.jpg', judul: 'Kelas SMK-3 dasar', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h15-3021-b891714ccb.jpg', judul: 'Bintal jasmani', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h15-3024-8bd64c54b5.jpg', judul: 'Peraturan baris-berbaris dan PPM', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h14-2820-4cf0502ef5.jpg', judul: 'Latihan PBB di lapangan', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h14-2825-54b113268d.jpg', judul: 'Pembinaan tupoksi Satpam', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h14-2826-acbc4ad954.jpg', judul: 'Barisan anggota saat pembinaan', kategori: 'Pelatihan' },
  { gambar: '/galeri/sec-h10-2028-f216e9bc94.jpg', judul: 'Seleksi administrasi calon anggota', kategori: 'Rekrutmen' },
  { gambar: '/galeri/sec-h10-2029-1fe79196c7.jpg', judul: 'Pengukuran postur tubuh', kategori: 'Rekrutmen' },
  { gambar: '/galeri/sec-h10-2032-df029ec854.jpg', judul: 'Wawancara calon anggota', kategori: 'Rekrutmen' },
  { gambar: '/galeri/sec-h10-2033-f89a59f425.jpg', judul: 'Pemeriksaan kesehatan', kategori: 'Rekrutmen' },
  { gambar: '/galeri/sec-h10-2034-bc12b559dd.jpg', judul: 'Upacara pelepasan anggota', kategori: 'Rekrutmen' },
  { gambar: '/galeri/cln-h09-137-04a93016c9.jpg', judul: 'Barisan pelamar tenaga kerja', kategori: 'Rekrutmen' },
  { gambar: '/galeri/cln-h09-139-c7864eb6b0.jpg', judul: 'Wawancara tenaga cleaning service', kategori: 'Rekrutmen' },
  { gambar: '/galeri/cln-h09-140-27f1cfc3eb.jpg', judul: 'Pengarahan calon tenaga kerja', kategori: 'Rekrutmen' },
  { gambar: '/galeri/cln-h11-161-179a90a440.jpg', judul: 'Pembersihan lobi gedung', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h11-162-743c21cce8.jpg', judul: 'Pembersihan area pabrik', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h11-163-b36b80b6d0.jpg', judul: 'Perawatan ruang tamu', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h12-166-ca0ed7883a.jpg', judul: 'Pembersihan wastafel', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h12-167-1056c437d9.jpg', judul: 'Pembersihan area toilet', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h12-168-a2bc7dd7f2.jpg', judul: 'Mopping area terbuka', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h12-169-4ff3c19c34.jpg', judul: 'Perawatan area kolam', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h13-172-77e8ad1ef9.jpg', judul: 'Pembersihan pintu kaca', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h13-173-ee7957972b.jpg', judul: 'Pembersihan jendela dan blind', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h13-174-36dba533aa.jpg', judul: 'Pembersihan tangga gedung', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h13-175-b6d7b45552.jpg', judul: 'Pembersihan toilet', kategori: 'Cleaning Service' },
  { gambar: '/galeri/cln-h14-182-01b10706a2.jpg', judul: 'Pramusaji menyiapkan hidangan', kategori: 'Pramusaji' },
  { gambar: '/galeri/cln-h14-183-fb9ed91ddb.jpg', judul: 'Pelayanan tamu di ruang kerja', kategori: 'Pramusaji' },
  { gambar: '/galeri/cln-h14-184-4bd830c3f7.jpg', judul: 'Penataan peralatan pantry', kategori: 'Pramusaji' },
  { gambar: '/galeri/cln-h15-190-86864b0017.jpg', judul: 'Pembekalan tenaga produksi', kategori: 'Manpower' },
  { gambar: '/galeri/cln-h15-192-20915eb927.jpg', judul: 'Tenaga kerja di lini produksi', kategori: 'Manpower' },
  { gambar: '/galeri/cln-h16-316-83e033c208.jpg', judul: 'Operator mesin dengan APD lengkap', kategori: 'Manpower' },
  { gambar: '/galeri/cln-h16-317-6168d035ea.jpg', judul: 'Pergantian shift karyawan', kategori: 'Manpower' },
]
